= My First Walkthrough

// This is a template meant to be used as a starting point for walkthrough development

[time=12]
== Doing the first task

// Subtasks are not required. 
// For simple walkthroughs, create your procedure under tasks.

=== Subtask Title

. Do first step.
. Do second step.

[type=taskResource]
.Useful links
****
* link:https://google.com[Task related link]
****

[type=walkthroughResource,serviceName=openshift]
.OpenShift
****
* link:{openshift-host}[Openshift Console, window="_blank"]
****

[type=verification]
Check that the dashboard of service X reports no errors.

[type=verificationFail]
Try turning it off and on again.

OpenShift App Host: {openshift-app-host}
CodeReady Workspaces URL: {che-url}.
Fuse URL: {fuse-url}
Launcher URL: {launcher-url}
API Management URL: {api-management-url}
AMQ Online URL: {enmasse-url}
AMQ Online Broker URL: {enmasse-broker-url}
AMQ Online Credential Username: {enmasse-credentials-username}
AMQ Online Credential Password: {enmasse-credentials-password}

{route-frontend-host}

. Log into the link:{route-cakephp-mysql-example-host}[CakePHP app].